catalog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    
    url(r'^books/$', views.BookListView.as_view(), name = 'books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), 
        name = 'book-detail'),
    
    url(r'^authors/$', views.AuthorListView.as_view(), name = 'authors'),
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(),
        name = 'author-detail'),
    
    url(r'^eras/$', views.EraListView.as_view(), name = 'eras'),
    url(r'^era/(?P<pk>\d+)$', views.EraDetailView.as_view(),
        name = 'era-detail'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url = '/catalog/', permanent = True)),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
import uuid

# Create your models here.

class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    
    name = models.CharField(max_length = 200, 
        help_text = "Enter a book genre")
        
    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        
        return self.name
    
class Language(models.Model):
    """
    Model representing a Language (e.g. English, French, etc)
    """
    
    name = models.CharField(max_length = 200,
        help_text = "Enter the book's natural language")
        
    def __str__(self):
        """
        String for representing the Model object (in Admin sit etc.)
        """
        
        return self.name
        
class Era(models.Model):
    """
    Model representing a Era
    """
    
    name = models.CharField(max_length = 25,
        help_text = "Enter the era of the Star Wars universe")

    def get_absolute_url(self):
        return reverse('era-detail', args=[str(self.id)])
        
    def __str__(self):
        return self.name
        
class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    
    title = models.CharField(max_length = 200)
    
    author = models.ForeignKey('Author', on_delete = models.SET_NULL, 
        null = True)
    
    summary = models.TextField(max_length = 1000, 
        help_text = "Enter a brief description of the book")

    isbn = models.CharField('ISBN', max_length=17, 
        help_text='17 Character <a href="https://www.isbn-international' +
            '.org/content/what-isbn">ISBN number</a>')
        
    genre = models.ManyToManyField(Genre,
        help_text = "Select a genre for this book")
    
    language = models.ForeignKey('Language', on_delete = models.SET_NULL,
        null = True)
        
    era = models.ForeignKey('Era', on_delete = models.SET_NULL,
        null = True)
        
    action_time = models.CharField(max_length = 20, null = True,
        help_text = "Enter the time of action")
    
    def display_genre(self):
        """
        Creates a string for a Genre.
        This is required to display genre Admin
        """
        
        return ', '.join([genre.name for genre in self.genre.all()[:3]])
        
    display_genre.short_description = 'Genre'
    
    def __str__(self):
        """
        String for representing the Model object
        """
        
        return self.title
        
    def get_absolute_url(self):
        """
        Returns the url to access a particular bookinstance
        """
        
        return reverse('book-detail', args = [str(self.id)])
        
class BookInstance(models.Model):
    """
    Model representing a specific copy of a book
    (i.e. that can be boorowed from library)
    """
    
    id = models.UUIDField(primary_key = True, default = uuid.uuid4,
        help_text = "Unique ID for this particular book across whole library")
        
    book = models.ForeignKey('Book', on_delete = models.SET_NULL, null = True)
    
    imprint = models.CharField(max_length = 200)
    
    due_back = models.DateField(null = True, blank = True)
    
    borrower = models.ForeignKey(User, on_delete = models.SET_NULL,
        null = True, blank = True)
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
            
        return False
        
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    
    status = models.CharField(max_length = 1, choices = LOAN_STATUS,
        blank = True, default = 'm', help_text = 'Book availability')
    
    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)
        
    def __str__(self):
        """
        String for representing the Model object
        """
       
        return '{} ({})'.format(self.id, self.book.title)
        
class Author(models.Model):
    """
    Model representong an author
    """
    
    first_name = models.CharField(max_length = 100)
    
    last_name = models.CharField(max_length = 100)
    
    date_of_birth = models.DateField(null = True, blank = True)
    
    date_of_death = models.DateField('died', null = True, blank = True)
    
    class Meta:
        ordering = ['last_name', 'first_name']
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance
        """
        
        return reverse('author-detail', args = [str(self.id)])
        
    def __str__(self):
        """
        String for representing the Model object
        """
        
        return '{}, {}'.format(self.last_name, self.first_name)

catalog/views.py
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre, Era
from django.views import generic

# Create your views here.

def index(request):
    """
    Display function for the site's home page.
    """

    # Generate "quantities" of some of the main objects
    num_books = Book.objects.all().count()
    
    num_instances = BookInstance.objects.all().count()
    
    num_genres = Genre.objects.all().count()
    
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact = 'a').count()
    
    num_authors = Author.objects.count()

    num_eras = Era.objects.count()
    
    # Rendering an HTML template index.html with data inside
    # of the context variable "context"
    
    return render(
        request,
        'index.html',
        context = {'num_books': num_books, 'num_instances': num_instances,
            'num_instances_available': num_instances_available,
            'num_authors': num_authors, 'num_genres': num_genres,
            'num_eras': num_eras,}
    )
    
class BookListView(generic.ListView):
    model = Book
    
    paginate_by = 10
        
class BookDetailView(generic.DetailView):
    model = Book
    
class AuthorListView(generic.ListView):
    model = Author
    
    paginate_by = 10
    
class AuthorDetailView(generic.DetailView):
    model = Author
    
class EraListView(generic.ListView):
    model = Era
    
    paginate_by = 10
    
class EraDetailView(generic.DetailView):
    model = Era

catalog/templates/base_generic.html
<!Doctype html>
<html lang="ru">
    <head>
        {% block title %}<title>Star Wars Library</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
        <!-- Adding an additional static CSS file  -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Домашняя страница</a></li>
                        <li><a href="{% url 'books' %}">Все книги</a></li>
                        <li><a href="{% url 'authors' %}">Все авторы</a></li>
                        <li><a href="{% url 'eras' %}">Все эпохи</a></li>
                    </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10">
                    {% block content %}
                    {% endblock %}
                    
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{page_obj.previous_page_number}}">Предыдущая страница</a>
                                    {% endif %}
                                    <span class="page-current">
                                        Страница {{ page_obj.number }} из
                                        {{ page_obj.paginator.num_pages }}.
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{ request.path }}?page={{page_obj.next_page_number}}">Следующая страница</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Автор: {{ author.last_name }} {{ author.first_name }}</h1>
    
    <p>{% if author.date_of_birth != None %}{{ author.date_of_birth }} -{% endif %} {% if author.date_of_death != None %}{{author.date_of_death}}{% endif %}
    
    <div style="margin-top:20px">
        <h4>Книги автора</h4>
        
        <dl>
            {% for book in author.book_set.all %}
                <dt><a href="{% url 'book-detail' book.pk %}">{{ book }}</a>
            {% endfor %}
        </dl>
    </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список Авторов</h1>
    
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li>
                    <a href="{{ author.get_absolute_url }}">{{author.last_name }} {{author.first_name}}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>В библиотеке еще нет авторов.</p>
    {% endif %}
    
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Название: {{ book.title }}</h1>

    <p><strong>Автор:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
    <p><strong>Эпоха:</strong> <a href="{% url 'era-detail' book.era.pk %}">{{ book.era }}</a></p>
    <p><strong>Количество:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
    <p><strong>Язык:</strong> {{ book.language }}</p>  
    <p><strong>Жанр:</strong> {{ book.genre.all|join:", " }}</p>

    <div style="margin-top:20px">
        <h4>Копии</h4>

        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
            {% if copy.status != 'a' %}<p><strong>Дата возврата:</strong> {{copy.due_back}}</p>{% endif %}
            <p><strong>Отпечатано:</strong> {{copy.imprint}}</p>
            <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>

        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Список книг</h1>
    
    {% if book_list %}
        <ul>
            
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title}}</a>
                    ({{ book.author }})
                </li>
            {% endfor %}
            
        </ul>
    {% else %}
        <p>В библиотеке нет книг.</p>
    {% endif %}
            
{% endblock %}

catalog/templates/catalog/era_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Эпоха: {{ era.name }}</h1>
    
    <div style="margin-top:20px">
        <h4>Книги по данной эпохе:</h4>
        
        <dl>
            {% for book in era.book_set.all %}
                <dt><a href="{% url 'book-detail' book.pk %}">{{ book }}</a>
            {% endfor %}
        </dl>
    </div>
{% endblock %}

catalog/templates/catalog/era_list.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Список Эпох</h1>
    
    {%if era_list %}
    
        <ul>
            {% for era in era_list %}
                <li>
                    <a href="{{ era.get_absolute_url }}">{{ era.name }}</a>                
                </li>
            {% endfor %}
        </ul>
    {% else %}
            <p>На данный момент не добавлено ни одной эпохи.</p>    
    {% endif %}

{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
    <title>Тестовый сайт</title>
{% endblock %}

{% block content %}
    <h1>Домашняя страница библиотеки по Звездным Войнам</h1>

    <p>Добро пожаловать на <em>Star Wars Library</em>, веб-сайт Django,разработанный в качестве тестового примера</p>

    <h2>Имеющийся контент</h2>

    <p>Библиотека имеет следующее количество записей:</p>
    <ul>
        <li><strong>Книги:</strong> {{ num_books }}</li>
        <li><strong>Копии:</strong> {{ num_instances }}</li>
        <li><strong>Доступные копии:</strong> {{num_instances_available }}</li>
        <li><strong>Авторы:</strong> {{ num_authors }}</li>
        <li><strong>Жанры:</strong> {{ num_genres }}</li>
        <li><strong>Эпохи:</strong> {{ num_eras }}</li>
    </ul>
{% endblock %}